const Restaurant = [
  "Subway",
  "McDonalds",
  "Taco Bell",
  "Wendys",
  "Burger King",
  "Dunkin",
  "KFC",
  "Little Caesars Pizza",
  "Chipotle",
  "Papa Johns Pizza",
  "Arbys",
  "Popeyes",
  "Panda Express",
  "Panera Bread",
  "Chick-fil-A",
  "Jack in the Box",
  "Jimmy Johns Sandwiches",
  "Jersey Mikes Subs",
  "Dairy Queen",
  "IHOP",
  "Applebees Grill & Bar",
  "Starbucks",
  "Wingstop",
  "Five Guys Burgers & Fries",
  "Sonic Drive-In",
  "Dennys",
  "Its Just Wings",
  "Buffalo Wild Wings",
  "The Ice Cream Shop",
  "Smoothie King",
  "Chilis",
  "Firehouse Subs",
  "Hardees",
  "Tropical Smoothie Cafe",
  "Papa Murphys Take N Bake Pizza",
  "Tender Shack",
  "Wawa",
  "Outback Steakhouse",
  "Belo Pizzeria",
  "Cold Stone Creamery",
  "Zaxbys",
  "Auntie Annes",
  "Red Lobster",
  "Churchs Chicken",
  "Cracker Barrel",
  "Caseys",
  "Carls Jr.",
  "Marcos Pizza",
  "Qdoba Mexican Eats",
  "DELETE",
];

export default Restaurant;
